title: Prasanna (bala) - Deep Learning Jounrney
description: This is what i have learnt from Coursera's deeplearing.ai, Fast.ai, Convolutional Neural Networks for Visual Recognition.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
linkedin: https://www.linkedin.com/in/balaprasanna
fb: https://www.facebook.com/Meprasanna
twitter: https://twitter.com/balaissvp