title: $whoami = Bala
description: Software Engineer | AI Researcher | Coder { Python, Go, JS }
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
linkedin: 'https://www.linkedin.com/in/balaprasanna'
fb: 'https://www.facebook.com/Meprasanna'
twitter: 'https://twitter.com/balaissvp'